### ISSUE TITLE
Api Error

### ISSUE THREAD

**Issue by ZeyaMustafa** [coniferousdyer/Food-Ordering-Portal#61]
I cloned your project to learn about react and node js , there's an error with your api. Everytime I try to register or login there's an error. The database Is created in mongo db but the data is not pushed in it.
<img width="956" alt="Screenshot 2023-04-13 233115" src="https://user-images.githubusercontent.com/88560434/231845683-ce712765-0748-46d0-a7d9-6112d5a7e9d1.png">

**Comment by ZeyaMustafa** [comment]
<img width="950" alt="image" src="https://user-images.githubusercontent.com/88560434/231851967-6e32bdeb-b1f0-4f3b-95a4-693fa5a3ab0d.png">

**Comment by tim5chneider** [comment]
@ZeyaMustafa How did you fixed it?
